@extends('layouts.dashboard.main') @section('content')
<div class="d-flex justify-content-between mb-6"><div><h2>{{$family->dafacRecord?->reference_number??'Affected Family #'.$family->id}}</h2><div class="text-muted">{{$family->household_head_full_name}}</div></div>@include('disaster.partials.status-badge',['status'=>$family->status->value])</div>
<div class="card card-flush shadow-sm mb-6"><div class="card-body"><div class="row g-5">@foreach(['Disaster'=>$family->disaster?->name,'Barangay'=>$family->barangay?->name,'Evacuation Center'=>$family->evacuationCenter?->name??'Unassigned','Address'=>$family->complete_address,'Birthdate'=>$family->birthdate?->format('Y-m-d'),'Housing'=>$family->housing_condition,'Ownership'=>$family->house_ownership,'Contact'=>$family->contact_number] as $k=>$v)<div class="col-md-3"><div class="text-muted">{{$k}}</div><div class="fw-bold">{{$v?:'—'}}</div></div>@endforeach</div></div></div>
@php($tabs=['family'=>'Family Composition','duplicate'=>'Duplicate History','validation'=>'Validation','payroll'=>'Payroll / Payout','requirements'=>'Requirements','workflow'=>'Workflow History','audit'=>'Audit Trail'])
<ul class="nav nav-tabs nav-line-tabs mb-5">@foreach($tabs as $id=>$label)<li class="nav-item"><a class="nav-link {{$loop->first?'active':''}}" data-bs-toggle="tab" href="#{{$id}}">{{$label}}</a></li>@endforeach</ul><div class="tab-content card card-body">
<div class="tab-pane active" id="family"><table class="table"><thead><tr><th>Name</th><th>Birthdate</th><th>Relationship</th><th>Sex</th><th>Remarks</th></tr></thead><tbody>@foreach($family->familyMembers as $x)<tr><td>{{$x->name}}</td><td>{{$x->birthdate?->format('Y-m-d')}}</td><td>{{$x->relationship_to_head}}</td><td>{{$x->sex}}</td><td>{{$x->remarks_codes}}</td></tr>@endforeach</tbody></table></div>
<div class="tab-pane" id="duplicate">@forelse($family->duplicateChecks as $x)<div class="border-bottom py-3">Score {{$x->match_score}}% · {{$x->resolution}} · {{implode(', ',$x->matched_fields??[])}}</div>@empty No duplicate checks recorded. @endforelse</div>
<div class="tab-pane" id="validation">@forelse($family->validationRecords as $x)<div class="border-bottom py-3"><strong>{{$x->status}}</strong> · {{$x->validated_housing_condition}} · {{$x->notes}}</div>@empty No validation recorded. @endforelse</div>
<div class="tab-pane" id="payroll"><div>Payroll: {{$family->payrollRecord?->status??'Not prepared'}} · Amount: {{$family->payrollRecord?->amount??'—'}}</div>@foreach($family->payoutReleases as $x)<div class="border-top py-3">Payout {{$x->status}} · {{$x->assistance_kind}} · {{$x->amount}} · {{$x->released_at}}</div>@endforeach</div>
<div class="tab-pane" id="requirements">BFP: {{$family->postPayoutRequirement?->bfp_certificate_status??'Not started'}} · Barangay: {{$family->postPayoutRequirement?->barangay_certification_status??'Not started'}}</div>
<div class="tab-pane" id="workflow"><table class="table"><thead><tr><th>Date</th><th>Transition</th><th>Action</th><th>By</th><th>Remarks</th></tr></thead><tbody>@foreach($family->workflowHistories->sortByDesc('performed_at') as $x)<tr><td>{{$x->performed_at}}</td><td>{{$x->from_status}} → {{$x->to_status}}</td><td>{{$x->action}}</td><td>{{$x->performer?->name}}</td><td>{{$x->remarks}}</td></tr>@endforeach</tbody></table></div>
<div class="tab-pane" id="audit">@forelse($family->auditLogs->sortByDesc('created_at') as $x)<div class="border-bottom py-3">{{$x->created_at}} · {{$x->action}}</div>@empty Audit details are recorded on related records and workflow history. @endforelse</div></div>
@endsection
