@extends('layouts.dashboard.main')

@section('content')
<div class="released-payroll-toolbar d-flex justify-content-end mb-7">
    <form method="get" class="input-group search-box"><span class="input-group-text border-0 bg-white"><i class="ki-duotone ki-magnifier fs-3"><span class="path1"></span><span class="path2"></span></i></span><input name="search" value="{{request('search')}}" class="form-control border-0" placeholder="Search household, DAFAC, address..."><button class="btn btn-primary">Search</button></form>
</div>

<div class="row g-5 mb-7">
    <div class="col-md-6"><div class="metric-card card card-flush h-100"><div class="card-body d-flex align-items-center gap-5"><div class="metric-icon bg-light-success"><i class="ki-duotone ki-check-circle fs-2x text-success"><span class="path1"></span><span class="path2"></span></i></div><div><div class="fs-2hx fw-bold text-gray-900">{{number_format($totalReleased)}}</div><div class="text-muted fw-semibold">Successful Releases</div></div></div></div></div>
    <div class="col-md-6"><div class="metric-card card card-flush h-100"><div class="card-body d-flex align-items-center gap-5"><div class="metric-icon bg-light-primary"><i class="ki-duotone ki-dollar fs-2x text-primary"><span class="path1"></span><span class="path2"></span></i></div><div><div class="fs-2hx fw-bold text-gray-900">₱{{number_format((float)$totalAmount,2)}}</div><div class="text-muted fw-semibold">Total Amount Released</div></div></div></div></div>
</div>

<div class="card card-flush shadow-sm released-card"><div class="card-header border-0"><div class="card-title"><div><h3 class="mb-1">Paid Beneficiaries</h3><div class="text-muted fs-7">Most recently released payouts appear first.</div></div></div></div><div class="card-body pt-2">
    <div class="table-responsive"><table class="table align-middle table-row-dashed gy-5"><thead><tr class="text-muted fw-bold text-uppercase fs-7"><th>DAFAC</th><th>Household</th><th>Evacuation Center</th><th>Assistance</th><th>Amount</th><th>Status</th><th>Released</th><th class="text-end">Action</th></tr></thead><tbody>
    @forelse($families as $family)
        @php $release = $family->payoutReleases->first(); @endphp
        <tr><td><span class="fw-bold text-primary">{{$family->dafacRecord?->reference_number??'—'}}</span></td><td><div class="fw-bold text-gray-900">{{$family->household_head_full_name}}</div><div class="text-muted fs-7 mw-250px text-truncate">{{$family->complete_address}}</div></td><td>{{$release?->center?->name??$family->evacuationCenter?->name??'—'}}<div class="text-muted fs-7">{{$family->barangay?->name}}</div></td><td>{{$release?->assistance_kind??'Financial Assistance'}}<div class="text-muted fs-7">{{$release?->provider}}</div></td><td class="fw-bold text-gray-900">₱{{number_format((float)($release?->amount??0),2)}}</td><td><span class="badge badge-light-success px-3 py-2"><span class="bullet bullet-dot bg-success me-2"></span>Paid</span></td><td>{{$release?->released_at?->format('M d, Y')}}<div class="text-muted fs-7">{{$release?->released_at?->format('h:i A')}}</div></td><td class="text-end"><button type="button" class="btn btn-sm btn-primary open-release" data-family-id="{{$family->id}}">Open</button></td></tr>
    @empty <tr><td colspan="8"><div class="empty-state text-center py-15"><i class="ki-duotone ki-wallet fs-3x text-muted"><span class="path1"></span><span class="path2"></span><span class="path3"></span></i><h3 class="mt-5">No released payouts yet</h3><div class="text-muted">Beneficiaries will appear here after their assistance is released.</div></div></td></tr> @endforelse
    </tbody></table></div><div class="mt-5">{{$families->links()}}</div>
</div></div>
@endsection

@push('modals')
<div class="modal fade" id="releaseDetailsModal" tabindex="-1"><div class="modal-dialog modal-xl modal-dialog-centered modal-dialog-scrollable"><div class="modal-content overflow-hidden"><div class="modal-header released-modal-header"><div><span class="badge badge-light-success mb-2">Payment Completed</span><h2 class="mb-1" id="release-household-title"></h2><div class="text-muted" id="release-reference"></div></div><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body p-0">
<ul class="nav nav-tabs nav-line-tabs nav-line-tabs-2x px-7 pt-5 mb-0 fs-5 fw-bold" id="payroll-modal-tabs"><li class="nav-item"><button class="nav-link active" id="household-tab" data-bs-toggle="tab" data-bs-target="#household-pane" type="button">Household Information</button></li><li class="nav-item"><button class="nav-link" id="payout-info-tab" data-bs-toggle="tab" data-bs-target="#payout-info-pane" type="button">Payout Information</button></li><li class="nav-item"><button class="nav-link" id="requirements-tab" data-bs-toggle="tab" data-bs-target="#requirements-pane" type="button">Requirements</button></li></ul>
<div class="tab-content"><div class="tab-pane fade show active" id="household-pane"><div class="p-7"><div class="notice bg-light-primary rounded border border-primary border-dashed p-4 mb-7"><strong>Read-only DAFAC record.</strong> Household and family-composition information cannot be edited from Payroll.</div><h4 class="section-title">Household Head & DAFAC Information</h4><div id="household-details" class="details-grid details-grid-wide mb-8"></div><h4 class="section-title">Family Composition</h4><div class="table-responsive border rounded"><table class="table align-middle table-row-dashed mb-0"><thead><tr class="text-muted fw-bold fs-7 text-uppercase"><th>Name</th><th>Birthdate / Age</th><th>Relationship</th><th>Sex</th><th>Occupation</th><th>Health</th><th>Remarks</th></tr></thead><tbody id="payroll-family-members"></tbody></table></div></div></div>
<div class="tab-pane fade" id="payout-info-pane"><div class="row g-0"><div class="col-lg-7 p-7"><h4 class="section-title">Payout Information</h4><div id="payout-details" class="details-grid"></div></div><div class="col-lg-5 proof-panel p-7"><div class="d-flex justify-content-between align-items-center mb-4"><h4 class="mb-0">Payout Photo</h4><span class="badge badge-light-success">Verified Proof</span></div><div id="photo-frame" class="photo-frame"><img id="release-photo" class="img-fluid rounded d-none" alt="Payout proof"><div id="no-release-photo" class="text-center text-muted py-15"><i class="ki-duotone ki-picture fs-3x"><span class="path1"></span><span class="path2"></span></i><div class="mt-3">No payout photo available.</div></div></div><div id="photo-caption" class="text-muted fs-7 mt-3"></div></div></div></div>
<div class="tab-pane fade" id="requirements-pane"><form id="requirements-form" class="p-7"><div id="requirements-alert" class="alert d-none"></div><div class="notice bg-light-primary rounded border border-primary border-dashed p-5 mb-7"><h4 class="mb-1">Post-Payout Documents</h4><div class="text-muted">Upload PDF, JPG, JPEG, or PNG files up to 8 MB each.</div></div><div class="row g-6"><div class="col-lg-6"><div class="requirement-upload-card h-100"><div class="d-flex justify-content-between align-items-start mb-5"><div class="requirement-icon bg-light-danger"><i class="ki-duotone ki-document fs-2x text-danger"><span class="path1"></span><span class="path2"></span></i></div><span id="bfp-status" class="badge badge-light-warning">Pending</span></div><h4>Bureau of Fire Protection (BFP) Certificate</h4><div id="bfp-file-name" class="text-muted fs-7 mb-4">No document uploaded.</div><input name="bfp_document" type="file" accept=".jpg,.jpeg,.png,.pdf" class="form-control"></div></div><div class="col-lg-6"><div class="requirement-upload-card h-100"><div class="d-flex justify-content-between align-items-start mb-5"><div class="requirement-icon bg-light-success"><i class="ki-duotone ki-geolocation fs-2x text-success"><span class="path1"></span><span class="path2"></span></i></div><span id="barangay-status" class="badge badge-light-warning">Pending</span></div><h4>Barangay Certification</h4><div id="barangay-file-name" class="text-muted fs-7 mb-4">No document uploaded.</div><input name="barangay_document" type="file" accept=".jpg,.jpeg,.png,.pdf" class="form-control"></div></div></div><div class="d-flex justify-content-end mt-7"><button id="save-requirements" class="btn btn-primary">Upload Requirements</button></div></form></div></div></div><div class="modal-footer"><button type="button" class="btn btn-primary" data-bs-dismiss="modal">Close</button></div></div></div></div>
@endpush

@push('styles')<style>
.released-payroll-toolbar{margin-top:1.25rem;padding:.75rem;border:1px solid var(--bs-gray-200);border-radius:1rem;background:rgba(255,255,255,.92);box-shadow:0 4px 18px rgba(24,28,50,.05)}.search-box{max-width:500px}.metric-card,.released-card{border:1px solid var(--bs-gray-200);box-shadow:0 5px 20px rgba(24,28,50,.06)}.released-card{border-radius:1rem}.metric-icon{width:60px;height:60px;border-radius:16px;display:grid;place-items:center}.released-modal-header{background:linear-gradient(135deg,#f1faff,#e8fff3);border-bottom:1px solid var(--bs-gray-200)}.proof-panel{background:#f8fafc;border-left:1px solid var(--bs-gray-200)}.photo-frame{min-height:320px;border:2px dashed var(--bs-gray-300);border-radius:1rem;background:white;display:grid;place-items:center;overflow:hidden}.photo-frame img{width:100%;max-height:480px;object-fit:contain}.details-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:1rem}.details-grid-wide{grid-template-columns:repeat(3,minmax(0,1fr))}.detail-item{padding:1rem;border:1px solid var(--bs-gray-200);border-radius:.75rem;background:#fff}.detail-label{color:var(--bs-gray-600);font-size:.8rem;margin-bottom:.25rem}.detail-value{color:var(--bs-gray-900);font-weight:600;word-break:break-word}.section-title{border-left:4px solid var(--bs-primary);padding-left:.75rem;margin-bottom:1.25rem}.requirement-upload-card{padding:1.5rem;border:1px solid var(--bs-gray-300);border-radius:1rem;background:#fff;box-shadow:0 3px 12px rgba(24,28,50,.05)}.requirement-icon{width:52px;height:52px;border-radius:14px;display:grid;place-items:center}@media(max-width:991px){.proof-panel{border-left:0;border-top:1px solid var(--bs-gray-200)}.details-grid-wide{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:575px){.details-grid,.details-grid-wide{grid-template-columns:1fr}.search-box{max-width:none;width:100%}.released-payroll-toolbar{margin-top:.75rem}}
</style>@endpush

@php
$payrollModalRecords = $families->getCollection()->mapWithKeys(function ($family) {
    $release = $family->payoutReleases->first();
    $requirement = $family->postPayoutRequirement;
    $memberComposition = $family->familyMembers->map(fn ($member) => ['name'=>$member->name,'birthdate'=>$member->birthdate?->format('Y-m-d'),'age'=>$member->age,'relationship'=>$member->relationship_to_head,'sex'=>$member->sex,'occupation'=>$member->occupation,'health'=>$member->health_condition,'remarks'=>$member->remarks_codes])->values();
    return [$family->id => ['reference'=>$family->dafacRecord?->reference_number,'surname'=>$family->household_head_surname,'given_name'=>$family->household_head_given_name,'middle_name'=>$family->household_head_middle_name,'household'=>$family->household_head_full_name,'birthdate'=>$family->birthdate?->format('Y-m-d'),'age'=>$family->age,'occupation'=>$family->occupation,'monthly_income'=>$family->monthly_income,'contact'=>$family->contact_number,'address'=>$family->complete_address,'barangay'=>$family->barangay?->name,'center'=>$release?->center?->name??$family->evacuationCenter?->name,'members'=>$family->familyMembers->count()+1,'member_composition'=>$memberComposition,'ownership'=>$family->house_ownership,'housing'=>$family->housing_condition,'health'=>$family->health_condition,'status'=>'Paid','assistance'=>$release?->assistance_kind,'quantity'=>$release?->quantity,'amount'=>$release?->amount,'provider'=>$release?->provider,'released_at'=>$release?->released_at?->format('M d, Y h:i A'),'released_by'=>$release?->releaser?->name,'caption'=>$release?->photo_caption,'photo'=>$release?->payout_photo_path?route('disaster.payroll.photo',$release):null,'requirements_url'=>route('disaster.payroll.requirements',$family),'bfp_status'=>$requirement?->bfp_certificate_status??'Pending','barangay_status'=>$requirement?->barangay_certification_status??'Pending','bfp_name'=>$requirement?->documents->where('document_type','bfp_document')->sortByDesc('id')->first()?->original_name,'barangay_name'=>$requirement?->documents->where('document_type','barangay_document')->sortByDesc('id')->first()?->original_name]];
});
@endphp
@push('scripts')<script>
(()=>{const records=@json($payrollModalRecords);const modal=new bootstrap.Modal('#releaseDetailsModal'),esc=v=>String(v??'—').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c])),grid=data=>Object.entries(data).map(([label,value])=>`<div class="detail-item"><div class="detail-label">${esc(label)}</div><div class="detail-value">${esc(value)}</div></div>`).join('');document.querySelectorAll('.open-release').forEach(button=>button.onclick=()=>{const r=records[button.dataset.familyId];document.querySelector('#release-household-title').textContent=r.household;document.querySelector('#release-reference').textContent=r.reference||'No DAFAC reference';document.querySelector('#household-details').innerHTML=grid({'Surname':r.surname,'Given Name':r.given_name,'Middle Name':r.middle_name,'Birthdate / Age':`${r.birthdate||'—'} / ${r.age??'—'}`,'Occupation':r.occupation,'Monthly Income':r.monthly_income,'Contact Number':r.contact,'Complete Address':r.address,'Barangay':r.barangay,'Evacuation Center':r.center,'House Ownership':r.ownership,'Housing Condition':r.housing,'Health Condition':r.health,'Household Size':r.members,'Status':r.status});document.querySelector('#payroll-family-members').innerHTML=r.member_composition.length?r.member_composition.map(member=>`<tr><td class="fw-semibold">${esc(member.name)}</td><td>${esc(member.birthdate)} / ${esc(member.age)}</td><td>${esc(member.relationship)}</td><td>${esc(member.sex)}</td><td>${esc(member.occupation)}</td><td>${esc(member.health)}</td><td>${esc(member.remarks)}</td></tr>`).join(''):'<tr><td colspan="7" class="text-center text-muted py-8">No additional family members recorded.</td></tr>';document.querySelector('#payout-details').innerHTML=grid({'Assistance Type':r.assistance,'Quantity':r.quantity,'Amount':`₱${Number(r.amount||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}`,'Provider':r.provider,'Released On':r.released_at,'Released By':r.released_by,'Status':r.status});const image=document.querySelector('#release-photo'),empty=document.querySelector('#no-release-photo');if(r.photo){image.src=r.photo;image.classList.remove('d-none');empty.classList.add('d-none')}else{image.removeAttribute('src');image.classList.add('d-none');empty.classList.remove('d-none')}document.querySelector('#photo-caption').textContent=r.caption||'';modal.show()})})();
(()=>{const records=@json($payrollModalRecords),csrf=document.querySelector('meta[name=csrf-token]').content;let active;const badge=(element,status)=>{element.textContent=status;element.className=`badge badge-light-${status==='Verified'?'success':status==='Submitted'?'primary':'warning'}`},populate=r=>{active=r;badge(document.querySelector('#bfp-status'),r.bfp_status);badge(document.querySelector('#barangay-status'),r.barangay_status);document.querySelector('#bfp-file-name').textContent=r.bfp_name||'No document uploaded.';document.querySelector('#barangay-file-name').textContent=r.barangay_name||'No document uploaded.';document.querySelector('#requirements-form').reset();document.querySelector('#requirements-alert').classList.add('d-none');bootstrap.Tab.getOrCreateInstance(document.querySelector('#household-tab')).show()};document.querySelectorAll('.open-release').forEach(button=>button.addEventListener('click',()=>populate(records[button.dataset.familyId])));document.querySelector('#requirements-form').addEventListener('submit',async event=>{event.preventDefault();if(!active)return;const button=document.querySelector('#save-requirements'),alertBox=document.querySelector('#requirements-alert'),fd=new FormData(event.target);button.disabled=true;alertBox.classList.add('d-none');try{const response=await fetch(active.requirements_url,{method:'POST',headers:{Accept:'application/json','X-CSRF-TOKEN':csrf},body:fd}),payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.message||Object.values(payload.errors||{}).flat().join('\n')||'Requirements could not be uploaded.');Object.assign(active,payload.data);populate(active);bootstrap.Tab.getOrCreateInstance(document.querySelector('#requirements-tab')).show();alertBox.textContent=payload.message;alertBox.className='alert alert-success'}catch(error){alertBox.textContent=error.message;alertBox.className='alert alert-danger'}finally{button.disabled=false}})})();
</script>@endpush
