@extends('layouts.dashboard.main')

@section('content')
<div class="row g-5 mb-8">
    @foreach([['People received',$totalPeople,'primary','profile-user'],['Status events',$totalEvents,'success','abstract-26'],['Latest API update',$latestReceivedAt ? \Illuminate\Support\Carbon::parse($latestReceivedAt)->format('M d, Y h:i A') : 'No data yet','warning','time']] as [$label,$value,$color,$icon])
    <div class="col-md-4"><div class="card card-flush h-100 shadow-sm"><div class="card-body d-flex align-items-center gap-5"><span class="symbol symbol-55px"><span class="symbol-label bg-light-{{$color}}"><i class="ki-duotone ki-{{$icon}} fs-2x text-{{$color}}"><span class="path1"></span><span class="path2"></span><span class="path3"></span><span class="path4"></span></i></span></span><div><div class="fs-{{is_numeric($value)?'2':'6'}} fw-bold text-gray-900">{{is_numeric($value)?number_format($value):$value}}</div><div class="text-muted fw-semibold">{{$label}}</div></div></div></div></div>
    @endforeach
</div>

<div class="card card-flush shadow-sm">
    <div class="card-header align-items-center py-5"><div class="card-title"><div><h3 class="fw-bold mb-1">Person Affected</h3><div class="text-muted fs-7">Resident records received through the TCISS API.</div></div></div><div class="card-toolbar"><span class="badge badge-light-primary">{{$people->total()}} {{Str::plural('record',$people->total())}}</span></div></div>
    <div class="card-body pt-0">
        <form method="GET" class="row g-4 mb-8 align-items-end"><div class="col-md-6"><label class="form-label">Resident or control number</label><input type="search" name="search" value="{{request('search')}}" class="form-control form-control-solid" placeholder="Search resident"></div><div class="col-md-3"><label class="form-label">Latest status</label><select name="status" class="form-select form-select-solid"><option value="">All statuses</option>@foreach($statuses as $option)<option value="{{$option}}" @selected(request('status')===$option)>{{Str::headline($option)}}</option>@endforeach</select></div><div class="col-md-3 d-flex gap-2"><button class="btn btn-primary flex-grow-1">Filter</button>@if(request()->query())<a href="{{route('disaster.person-affecteds.index')}}" class="btn btn-light">Clear</a>@endif</div></form>
        <div class="table-responsive"><table class="table align-middle table-row-dashed gy-5"><thead><tr class="text-gray-600 fw-bold fs-7 text-uppercase"><th>Resident</th><th>Latest Status</th><th>Date Tagged</th><th>Family</th><th>First Received</th><th></th></tr></thead><tbody>
        @forelse($people as $person)<tr><td><span class="fw-bold text-gray-900">{{$person->full_name ?: 'Resident record'}}</span><div class="text-primary fs-8">{{$person->control_number}}</div></td><td><span class="badge badge-light-danger">{{Str::headline($person->latestStatus?->status ?? 'Unknown')}}</span></td><td>{{$person->latestStatus?->date_tagged?->format('M d, Y h:i:s A') ?? '—'}}<div class="text-muted fs-8">{{$person->latestStatus?->date_tagged?->diffForHumans()}}</div></td><td>{{$person->family_members_count}} members</td><td>{{$person->created_at?->format('M d, Y h:i A') ?? '—'}}</td><td class="text-end"><button class="btn btn-sm btn-light-primary js-person-details" data-url="{{route('disaster.person-affecteds.show',$person)}}">Details</button></td></tr>
        @empty<tr><td colspan="6"><div class="text-center py-15"><i class="ki-duotone ki-profile-user fs-3x text-muted"><span class="path1"></span><span class="path2"></span></i><h4 class="mt-4">No person affected records found</h4><p class="text-muted">Records sent by the TCISS API will appear here automatically.</p></div></td></tr>@endforelse
        </tbody></table></div><div class="d-flex justify-content-end mt-5">{{$people->links()}}</div>
    </div>
</div>

<div class="modal fade" id="residentModal" tabindex="-1"><div class="modal-dialog modal-xl modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><div><div class="text-muted text-uppercase fs-8 fw-bold">Resident Record</div><h2 id="resident-name" class="mb-1">Resident</h2><div id="resident-control" class="text-primary fw-semibold"></div></div><button class="btn btn-sm btn-icon btn-light" data-bs-dismiss="modal"><i class="ki-duotone ki-cross fs-2"><span class="path1"></span><span class="path2"></span></i></button></div><div class="modal-body"><div id="resident-loading" class="text-center py-15"><span class="spinner-border text-primary"></span></div><div id="resident-content" class="d-none"><div class="row g-5 mb-5"><div class="col-lg-6"><div class="border rounded p-6 h-100"><h3>Personal Information</h3><div id="personal-info" class="detail-grid"></div></div></div><div class="col-lg-6"><div class="border rounded p-6 mb-5"><h3>Address</h3><div id="address-info" class="detail-grid"></div></div><div class="border rounded p-6"><h3>Family Information</h3><div id="family-info" class="detail-grid"></div></div></div></div><div class="border rounded p-6"><div class="d-flex justify-content-between"><h3>Family Composition</h3><span id="family-count" class="badge badge-light-primary"></span></div><div class="table-responsive"><table class="table table-row-dashed gy-4"><thead><tr><th>Control No.</th><th>Name</th><th>Relationship</th><th>Age</th><th>Sex</th><th>Code</th><th>Housing</th></tr></thead><tbody id="family-rows"></tbody></table></div></div></div></div></div></div></div>
@endsection

@push('styles')
<style>.detail-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:1rem 2rem}.detail-item.wide{grid-column:1/-1}.detail-label{color:#99a1b7;font-size:.78rem;margin-bottom:.15rem}.detail-value{color:#071437;font-weight:500}@media(max-width:575px){.detail-grid{grid-template-columns:1fr}}</style>
@endpush

@push('scripts')
<script>(()=>{const modal=new bootstrap.Modal(document.getElementById('residentModal'));const e=id=>document.getElementById(id);const esc=v=>String(v??'—').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));const money=v=>v===null||v===''?'—':new Intl.NumberFormat('en-PH',{style:'currency',currency:'PHP'}).format(v);const grid=(id,items)=>e(id).innerHTML=items.map(([k,v,w])=>`<div class="detail-item ${w?'wide':''}"><div class="detail-label">${esc(k)}</div><div class="detail-value">${esc(v)}</div></div>`).join('');document.querySelectorAll('.js-person-details').forEach(b=>b.onclick=async()=>{modal.show();e('resident-loading').classList.remove('d-none');e('resident-content').classList.add('d-none');try{const r=await fetch(b.dataset.url,{headers:{Accept:'application/json'}});if(!r.ok)throw new Error('Unable to load resident record.');const d=(await r.json()).data;e('resident-name').textContent=d.full_name||'Resident';e('resident-control').textContent=d.control_number;grid('personal-info',[['Birthday',d.birthdate],['Age',d.age],['Sex',d.sex],['Code',d.code],['Occupation',d.occupation,true],['Monthly Income',money(d.monthly_income),true],['Health Condition',d.health_condition,true]]);grid('address-info',[['District',d.district],['Barangay',d.barangay],['Street',d.street,true],['City',d.city,true]]);grid('family-info',[['Family Head',d.family_head_name,true],['Family Head CN',d.family_head_control_number,true],['Relationship',d.relationship],['Housing',d.housing]]);e('family-count').textContent=`${d.family_members.length} members`;e('family-rows').innerHTML=d.family_members.length?d.family_members.map(m=>`<tr><td>${esc(m.control_number)}</td><td>${esc(m.full_name)}</td><td>${esc(m.relationship)}</td><td>${esc(m.age)}</td><td>${esc(m.sex)}</td><td>${esc(m.code)}</td><td>${esc(m.housing)}</td></tr>`).join(''):'<tr><td colspan="7" class="text-center text-muted py-8">No family composition received.</td></tr>';e('resident-loading').classList.add('d-none');e('resident-content').classList.remove('d-none')}catch(x){e('resident-loading').innerHTML=`<div class="alert alert-danger">${esc(x.message)}</div>`}}})})();</script>
@endpush
