@extends('layouts.dashboard.main')

@section('content')
<div class="row g-5 mb-7 report-summary">
@foreach([['Households',$reportSummary['total'],'ki-people','primary'],['Validated',$reportSummary['validated'],'ki-shield-tick','success'],['Payout Released',$reportSummary['released'],'ki-dollar','info'],['Requirements Complete',$reportSummary['requirements_complete'],'ki-verify','warning']] as [$label,$value,$icon,$tone])
<div class="col-6 col-xl-3"><div class="card card-flush report-metric h-100"><div class="card-body d-flex align-items-center gap-4"><div class="report-icon bg-light-{{$tone}}"><i class="ki-duotone {{$icon}} fs-2x text-{{$tone}}"><span class="path1"></span><span class="path2"></span><span class="path3"></span></i></div><div><div class="fs-2hx fw-bold text-gray-900">{{number_format($value)}}</div><div class="text-muted fw-semibold fs-7">{{$label}}</div></div></div></div></div>
@endforeach
</div>

<div class="card card-flush shadow-sm mb-7 report-filters"><div class="card-header align-items-center"><div class="card-title"><div><h3 class="fw-bold mb-1">Report Filters</h3><div class="text-muted fs-7">Filter by household, location, validation, payout, and requirements.</div></div></div>@if(request()->query())<div class="card-toolbar"><a href="{{route('disaster.reports.index')}}" class="btn btn-sm btn-light-danger">Clear Filters</a></div>@endif</div><div class="card-body pt-2"><form method="get" class="row g-4 align-items-end">
<div class="col-md-6 col-xl-3"><label class="form-label">Search</label><div class="input-group"><span class="input-group-text border-0"><i class="ki-duotone ki-magnifier fs-3"><span class="path1"></span><span class="path2"></span></i></span><input name="search" value="{{request('search')}}" class="form-control form-control-solid" placeholder="Household, DAFAC, address"></div></div>
<div class="col-md-6 col-xl-3"><label class="form-label">Disaster / Incident</label><select name="disaster_id" class="form-select form-select-solid"><option value="">All disasters</option>@foreach($disasters as $x)<option value="{{$x->id}}" @selected(request('disaster_id')==$x->id)>{{$x->name}}</option>@endforeach</select></div>
<div class="col-md-6 col-xl-3"><label class="form-label">Barangay</label><select name="barangay_id" class="form-select form-select-solid"><option value="">All barangays</option>@foreach($barangays as $x)<option value="{{$x->id}}" @selected(request('barangay_id')==$x->id)>{{$x->name}}</option>@endforeach</select></div>
<div class="col-md-6 col-xl-3"><label class="form-label">Evacuation Center</label><select name="evacuation_center_id" class="form-select form-select-solid"><option value="">All centers</option>@foreach($centers as $x)<option value="{{$x->id}}" @selected(request('evacuation_center_id')==$x->id)>{{$x->name}}</option>@endforeach</select></div>
<div class="col-6 col-xl-2"><label class="form-label">Validation Status</label><select name="validation_status" class="form-select form-select-solid"><option value="">All statuses</option><option @selected(request('validation_status')==='Validated')>Validated</option><option @selected(request('validation_status')==='For Validation')>For Validation</option></select></div>
<div class="col-6 col-xl-2"><label class="form-label">Payout Status</label><select name="payout_status" class="form-select form-select-solid"><option value="">All payouts</option><option @selected(request('payout_status')==='Released')>Released</option><option @selected(request('payout_status')==='Pending')>Pending</option></select></div>
<div class="col-6 col-xl-2"><label class="form-label">Requirements</label><select name="requirements_status" class="form-select form-select-solid"><option value="">All requirements</option><option @selected(request('requirements_status')==='Complete')>Complete</option><option @selected(request('requirements_status')==='Incomplete')>Incomplete</option></select></div>
<div class="col-6 col-xl-2"><label class="form-label">Housing</label><select name="housing_condition" class="form-select form-select-solid"><option value="">All conditions</option>@foreach(['Totally Damaged','Partially Damaged','Water Damage'] as $x)<option @selected(request('housing_condition')===$x)>{{$x}}</option>@endforeach</select></div>
<div class="col-6 col-xl-2"><label class="form-label">Ownership</label><select name="house_ownership" class="form-select form-select-solid"><option value="">All ownership</option>@foreach(['Owner','Renter','Sharer'] as $x)<option @selected(request('house_ownership')===$x)>{{$x}}</option>@endforeach</select></div>
<div class="col-6 col-xl-2"><button class="btn btn-primary w-100"><i class="ki-duotone ki-filter fs-3"><span class="path1"></span><span class="path2"></span></i>Apply</button></div>
</form></div></div>

<div class="card card-flush shadow-sm report-results"><div class="card-header align-items-center"><div class="card-title"><div><h3 class="fw-bold mb-1">Household Assistance Report</h3><div class="text-muted fs-7">{{$families->total()}} {{Str::plural('household',$families->total())}} found</div></div></div><div class="card-toolbar"><button type="button" onclick="window.print()" class="btn btn-sm btn-light-primary"><i class="ki-duotone ki-printer fs-3"><span class="path1"></span><span class="path2"></span></i>Print / Save PDF</button></div></div><div class="card-body pt-2"><div class="table-responsive report-table"><table class="table align-middle table-row-dashed gy-5"><thead><tr class="text-muted fw-bold text-uppercase fs-7"><th>DAFAC / Household</th><th>Location</th><th>Household</th><th>Validation</th><th>Payout</th><th>Requirements</th><th class="text-end">Action</th></tr></thead><tbody>
@forelse($families as $family)
@php
$payout=$family->payoutReleases->first();
$validated=$family->validationRecords->contains('status','Validated');
$requirement=$family->postPayoutRequirement;
$requirementsComplete=$requirement?->bfp_certificate_status==='Verified'&&$requirement?->barangay_certification_status==='Verified';
@endphp
<tr><td><div class="fw-bold text-primary">{{$family->dafacRecord?->reference_number??'No DAFAC'}}</div><div class="fw-bold text-gray-900 mt-1">{{$family->household_head_full_name}}</div><div class="text-muted fs-7 text-truncate report-address">{{$family->complete_address}}</div></td><td><div class="fw-semibold">{{$family->barangay?->name??'—'}}</div><div class="text-muted fs-7">{{$family->evacuationCenter?->name??'Unassigned'}}</div><div class="text-muted fs-8">{{$family->disaster?->name}}</div></td><td><div class="fw-semibold">{{$family->familyMembers->count()+1}} total members</div><div class="text-muted fs-7">{{$family->housing_condition}} · {{$family->house_ownership}}</div><div class="text-muted fs-7">{{$family->health_condition?:'No health condition recorded'}}</div></td><td><span class="badge badge-light-{{$validated?'success':'warning'}} px-3 py-2">{{$validated?'Validated':'For Validation'}}</span></td><td>@if($payout?->status==='Released')<div class="badge badge-light-success px-3 py-2">Released</div><div class="fw-bold mt-2">₱{{number_format((float)$payout->amount,2)}}</div><div class="text-muted fs-8">{{$payout->released_at?->format('M d, Y')}}</div>@else<span class="badge badge-light-secondary px-3 py-2">Pending</span>@endif</td><td>@if(!$payout||$payout->status!=='Released')<span class="badge badge-light-secondary">Not Available</span>@else<span class="badge badge-light-{{$requirementsComplete?'success':'warning'}} px-3 py-2">{{$requirementsComplete?'Complete':'Incomplete'}}</span><div class="text-muted fs-8 mt-2">BFP: {{$requirement?->bfp_certificate_status??'Pending'}}<br>Barangay: {{$requirement?->barangay_certification_status??'Pending'}}</div>@endif</td><td class="text-end"><a href="{{route('disaster.families.show',$family)}}" class="btn btn-sm btn-light-primary">Open</a></td></tr>
@empty<tr><td colspan="7"><div class="text-center py-15"><div class="report-empty-icon mx-auto"><i class="ki-duotone ki-document fs-2x text-muted"><span class="path1"></span><span class="path2"></span></i></div><h3 class="mt-5 mb-1">No matching records</h3><div class="text-muted">Adjust or clear the filters and try again.</div></div></td></tr>@endforelse
</tbody></table></div><div class="d-flex justify-content-end mt-6">{{$families->links()}}</div></div></div>
@endsection

@push('styles')<style>
.report-metric,.report-results{border:1px solid var(--bs-gray-200);box-shadow:0 5px 20px rgba(24,28,50,.06)}.report-icon,.report-empty-icon{width:56px;height:56px;border-radius:15px;display:grid;place-items:center}.report-empty-icon{background:var(--bs-gray-100)}.report-address{max-width:300px}.report-table{min-height:280px}.report-results,.report-filters{border-radius:1rem}@media print{#kt_header,#kt_aside,.report-filters,.report-summary,.card-toolbar,.pagination{display:none!important}.wrapper{margin:0!important}.card{box-shadow:none!important;border:0!important}.report-table{overflow:visible!important}}
</style>@endpush
