@extends('layouts.dashboard.main')
@section('content')
<div class="card card-flush report-card">
 <div class="card-header border-0 pt-6 align-items-center"><div class="card-title d-block"><h2 class="fw-bold text-gray-900 mb-1">Evacuee Monitoring Report</h2><div class="text-muted fs-7">Build a filtered monitoring report and choose which headers to display.</div></div><div class="card-toolbar gap-3"><a href="{{route('disaster.reports.export',request()->query())}}" class="btn btn-light-success fw-bold"><i class="ki-duotone ki-file-down fs-3"><span class="path1"></span><span class="path2"></span></i>Export Excel</a><button class="btn btn-primary fw-bold" type="button" data-bs-toggle="offcanvas" data-bs-target="#reportConfigurator"><i class="ki-duotone ki-setting-4 fs-3"><span class="path1"></span><span class="path2"></span></i>Configure Report</button></div></div>
 <div class="card-body pt-5">
  <div class="d-flex flex-wrap justify-content-between align-items-center gap-4 mb-6"><select id="reportPageSize" class="form-select form-select-sm w-auto" aria-label="Rows per page"><option>10</option><option>25</option><option>50</option><option>100</option></select><div class="position-relative"><i class="ki-duotone ki-magnifier fs-3 position-absolute top-50 translate-middle-y ms-4"><span class="path1"></span><span class="path2"></span></i><input id="reportSearch" class="form-control form-control-sm w-250px ps-10" placeholder="Search report..."></div></div>
  <div class="table-responsive report-table-wrap"><table class="table align-middle table-row-bordered gy-4 mb-0" id="monitoringReportTable"><thead><tr>@foreach($selected as $key)<th class="text-uppercase text-nowrap">{{$columns[$key]}}</th>@endforeach</tr></thead><tbody>
  @forelse($rows as $row)<tr>@foreach($selected as $key)<td class="{{in_array($key,['district','barangay','evacuation_center'])?'fw-semibold text-gray-800':'text-center'}}">{{$row[$key]}}</td>@endforeach</tr>@empty<tr class="report-empty-row"><td colspan="{{count($selected)}}" class="text-center py-15"><i class="ki-duotone ki-information-5 fs-2x text-muted"><span class="path1"></span><span class="path2"></span><span class="path3"></span></i><div class="fw-bold mt-3">No evacuation centers found</div><div class="text-muted fs-7">Try changing the report filters.</div></td></tr>@endforelse
  </tbody>@if($rows->isNotEmpty())<tfoot><tr class="fw-bold">@foreach($selected as $key)<td class="{{in_array($key,['district','barangay','evacuation_center'])?'':'text-center'}}">{{$loop->first?'Grand Total':(in_array($key,['district','barangay','evacuation_center'])?'':number_format($rows->sum($key)))}}</td>@endforeach</tr></tfoot>@endif</table></div>
  <div class="d-flex flex-wrap justify-content-between align-items-center gap-3 mt-6"><div id="reportInfo" class="text-muted fs-7"></div><div id="reportPagination" class="d-flex align-items-center gap-2"></div></div>
 </div>
</div>

<div class="offcanvas offcanvas-end report-configurator" tabindex="-1" id="reportConfigurator" aria-labelledby="reportConfiguratorLabel"><form method="get" action="{{route('disaster.reports.index')}}" class="h-100 d-flex flex-column" id="reportConfigForm">
 <div class="offcanvas-header border-bottom px-7 py-5"><div><h3 id="reportConfiguratorLabel" class="fw-bold mb-1">Configure Monitoring Report</h3><div class="text-muted fs-7">Apply filters and choose the report headers.</div></div><button type="button" class="btn btn-sm btn-icon btn-light" data-bs-dismiss="offcanvas"><i class="ki-duotone ki-cross fs-2"><span class="path1"></span><span class="path2"></span></i></button></div>
 <div class="offcanvas-body px-7 py-6"><div class="row g-5">
  <div class="col-12"><label class="form-label fw-semibold">Incident</label><select name="disaster_id" class="form-select"><option value="">All incidents</option>@foreach($disasters as $disaster)<option value="{{$disaster->id}}" @selected((string)request('disaster_id')===(string)$disaster->id)>{{$disaster->name}} — {{$disaster->incident_date?->format('M d, Y')}}</option>@endforeach</select></div>
  <div class="col-md-6"><label class="form-label fw-semibold">District</label><select name="district" class="form-select"><option value="">All districts</option>@foreach($barangays->pluck('district')->filter()->unique()->sort() as $district)<option value="{{$district}}" @selected(request('district')===$district)>{{$district}}</option>@endforeach</select></div>
  <div class="col-md-6"><label class="form-label fw-semibold">Barangay</label><select name="barangay_id" class="form-select"><option value="">All barangays</option>@foreach($barangays as $barangay)<option value="{{$barangay->id}}" @selected((string)request('barangay_id')===(string)$barangay->id)>{{$barangay->name}}</option>@endforeach</select></div>
  <div class="col-12"><label class="form-label fw-semibold">Evacuation Center</label><select name="evacuation_center_id" class="form-select"><option value="">All evacuation centers</option>@foreach($centers as $center)<option value="{{$center->id}}" @selected((string)request('evacuation_center_id')===(string)$center->id)>{{$center->name}}</option>@endforeach</select></div>
  <div class="col-md-6"><label class="form-label fw-semibold">Registered From</label><input type="date" name="date_from" value="{{request('date_from')}}" class="form-control"></div><div class="col-md-6"><label class="form-label fw-semibold">Registered To</label><input type="date" name="date_to" value="{{request('date_to')}}" class="form-control"></div>
 </div><div class="separator my-7"></div><div class="d-flex justify-content-between align-items-center mb-5"><div class="fw-bold fs-5"><i class="ki-duotone ki-row-horizontal text-primary fs-3 me-2"><span class="path1"></span><span class="path2"></span></i>Headers</div><div class="d-flex gap-4"><button type="button" class="btn btn-link btn-sm p-0" id="selectAllHeaders">Select All</button><button type="button" class="btn btn-link btn-sm text-muted p-0" id="defaultHeaders">Use Defaults</button></div></div>
 @php($headerGroups = [
  'Location' => ['district', 'barangay', 'evacuation_center'],
  'Population' => ['families', 'individuals', 'staff'],
  'Gender' => ['male', 'female'],
  'Age' => ['age_0_4', 'age_5_17', 'age_18_59', 'age_60_plus'],
  'Sector' => ['pwd', 'solo_parent', 'lactating', 'pregnant', 'four_ps'],
 ])
 <div id="reportHeaders">@foreach($headerGroups as $groupLabel => $groupColumns)<div class="report-header-group mb-6"><div class="fw-bold text-gray-900 mb-4">{{$groupLabel}}</div><div class="row g-4 ps-8">@foreach($groupColumns as $key)<div class="col-6"><label class="form-check form-check-custom form-check-solid"><input class="form-check-input report-column" type="checkbox" name="columns[]" value="{{$key}}" @checked(in_array($key,$checkedColumns))><span class="form-check-label text-gray-700">{{$columns[$key]}}</span></label></div>@endforeach</div></div>@endforeach</div></div>
 <div class="border-top px-7 py-5 d-flex justify-content-end gap-3 bg-body"><a href="{{route('disaster.reports.index')}}" class="btn btn-light">Reset</a><button class="btn btn-primary" type="submit"><i class="ki-duotone ki-check fs-3"><span class="path1"></span><span class="path2"></span></i>Apply Report</button></div>
</form></div>
@endsection

@push('styles')<style>
.report-card{border:1px solid var(--bs-gray-200);border-radius:1rem;box-shadow:0 6px 24px rgba(31,53,89,.07)}.report-card thead th{background:#1f4e78;color:#fff!important;text-align:center;padding:1rem .85rem;font-size:.78rem;letter-spacing:.02em;border-bottom:0}.report-card thead th:first-child{border-radius:.65rem 0 0 .65rem}.report-card thead th:last-child{border-radius:0 .65rem .65rem 0}.report-card tfoot td{background:#d9eaf7;border-top:2px solid #1f4e78}.report-table-wrap{min-height:300px}.report-configurator{width:min(610px,100vw)!important}.report-configurator .offcanvas-body{overflow-y:auto}.page-btn{width:34px;height:34px;border:0;border-radius:9px;background:transparent;color:var(--bs-gray-600)}.page-btn.active{background:var(--bs-primary);color:#fff}.page-btn:disabled{opacity:.35}@media(max-width:767px){.report-card .card-header{gap:1rem}.report-card .card-toolbar{width:100%}.report-card .card-toolbar .btn{flex:1}.w-250px{width:210px!important}}
</style>@endpush

@push('scripts')<script>
document.addEventListener('DOMContentLoaded',function(){const bodyRows=[...document.querySelectorAll('#monitoringReportTable tbody tr:not(.report-empty-row)')],search=document.getElementById('reportSearch'),size=document.getElementById('reportPageSize'),info=document.getElementById('reportInfo'),pager=document.getElementById('reportPagination');let page=1;function render(){const term=search.value.trim().toLowerCase(),visible=bodyRows.filter(row=>row.innerText.toLowerCase().includes(term)),per=Number(size.value),pages=Math.max(1,Math.ceil(visible.length/per));page=Math.min(page,pages);bodyRows.forEach(row=>row.hidden=true);visible.slice((page-1)*per,page*per).forEach(row=>row.hidden=false);const start=visible.length?(page-1)*per+1:0,end=Math.min(page*per,visible.length);info.textContent=`Showing ${start} to ${end} of ${visible.length} evacuation centers`;pager.innerHTML='';const button=(text,target,disabled,active=false)=>{const b=document.createElement('button');b.type='button';b.className='page-btn'+(active?' active':'');b.textContent=text;b.disabled=disabled;b.onclick=()=>{page=target;render()};pager.appendChild(b)};button('‹',page-1,page===1);for(let p=1;p<=pages;p++)if(p===1||p===pages||Math.abs(p-page)<=1)button(p,p,false,p===page);else if(!pager.lastElementChild||pager.lastElementChild.textContent!=='…')button('…',page,true);button('›',page+1,page===pages)}search.addEventListener('input',()=>{page=1;render()});size.addEventListener('change',()=>{page=1;render()});render();const checks=[...document.querySelectorAll('.report-column')];document.getElementById('selectAllHeaders').onclick=()=>checks.forEach(c=>c.checked=true);document.getElementById('defaultHeaders').onclick=()=>checks.forEach(c=>c.checked=true);document.getElementById('reportConfigForm').addEventListener('submit',e=>{if(!checks.some(c=>c.checked)){e.preventDefault();alert('Select at least one report header.')}})});
</script>@endpush
