@extends('layouts.dashboard.main')

@section('content')
<div class="card card-flush shadow-sm mb-7 report-filters">
    <div class="card-header align-items-center"><div class="card-title"><div><h3 class="fw-bold mb-1">Report Filters</h3><div class="text-muted fs-7">Narrow the connected household records by location, workflow, and housing details.</div></div></div>@if(request()->hasAny(['disaster_id','barangay_id','evacuation_center_id','status','housing_condition','house_ownership','date_from','date_to']))<div class="card-toolbar"><a href="{{route('disaster.reports.index')}}" class="btn btn-sm btn-light-danger">Clear filters</a></div>@endif</div>
    <div class="card-body pt-2"><form method="get" class="row g-4 align-items-end">
        <div class="col-md-6 col-xl-3"><label class="form-label">Disaster / Incident</label><select name="disaster_id" class="form-select form-select-solid"><option value="">All disasters</option>@foreach($disasters as $x)<option value="{{$x->id}}" @selected(request('disaster_id')==$x->id)>{{$x->name}}</option>@endforeach</select></div>
        <div class="col-md-6 col-xl-3"><label class="form-label">Barangay</label><select name="barangay_id" class="form-select form-select-solid"><option value="">All barangays</option>@foreach($barangays as $x)<option value="{{$x->id}}" @selected(request('barangay_id')==$x->id)>{{$x->name}}</option>@endforeach</select></div>
        <div class="col-md-6 col-xl-3"><label class="form-label">Evacuation Center</label><select name="evacuation_center_id" class="form-select form-select-solid"><option value="">All centers</option>@foreach($centers as $x)<option value="{{$x->id}}" @selected(request('evacuation_center_id')==$x->id)>{{$x->name}}</option>@endforeach</select></div>
        <div class="col-md-6 col-xl-3"><label class="form-label">Workflow Status</label><select name="status" class="form-select form-select-solid"><option value="">All workflow statuses</option>@foreach(\App\Enums\FamilyStatus::cases() as $x)<option value="{{$x->value}}" @selected(request('status')===$x->value)>{{str_replace('_',' ',$x->value)}}</option>@endforeach</select></div>
        <div class="col-md-6 col-xl-3"><label class="form-label">Housing Condition</label><select name="housing_condition" class="form-select form-select-solid"><option value="">All housing conditions</option>@foreach(['Totally Damaged','Partially Damaged','Water Damage'] as $x)<option @selected(request('housing_condition')===$x)>{{$x}}</option>@endforeach</select></div>
        <div class="col-md-6 col-xl-3"><label class="form-label">House Ownership</label><select name="house_ownership" class="form-select form-select-solid"><option value="">All ownership types</option>@foreach(['Owner','Renter','Sharer'] as $x)<option @selected(request('house_ownership')===$x)>{{$x}}</option>@endforeach</select></div>
        <div class="col-6 col-xl-2"><label class="form-label">Created From</label><input type="date" name="date_from" value="{{request('date_from')}}" class="form-control form-control-solid"></div>
        <div class="col-6 col-xl-2"><label class="form-label">Created To</label><input type="date" name="date_to" value="{{request('date_to')}}" class="form-control form-control-solid"></div>
        <div class="col-xl-2"><button class="btn btn-primary w-100"><i class="ki-duotone ki-filter fs-3"><span class="path1"></span><span class="path2"></span></i>Run Report</button></div>
    </form></div>
</div>

<div class="card card-flush shadow-sm"><div class="card-header align-items-center"><div class="card-title"><div><h3 class="fw-bold mb-1">End-to-End Workflow Report</h3><div class="text-muted fs-7">{{$families->total()}} connected {{Str::plural('household',$families->total())}} found</div></div></div><div class="card-toolbar"><button type="button" onclick="window.print()" class="btn btn-sm btn-light-primary"><i class="ki-duotone ki-printer fs-3"><span class="path1"></span><span class="path2"></span></i>Print / Save PDF</button></div></div>
<div class="card-body pt-2"><div class="table-responsive report-table"><table class="table align-middle table-row-dashed gy-5"><thead><tr class="text-muted fw-bold text-uppercase fs-7"><th>DAFAC / Household</th><th>Location</th><th>Household</th><th>Housing</th><th>Workflow</th><th>Payout</th><th class="text-end">Action</th></tr></thead><tbody>
@forelse($families as $family) @php($payout=$family->payoutReleases->sortByDesc('id')->first())<tr><td><strong>{{$family->dafacRecord?->reference_number??'No DAFAC'}}</strong><div class="fw-semibold mt-1">{{$family->household_head_full_name}}</div><div class="text-muted fs-7 text-truncate report-address">{{$family->complete_address}}</div></td><td>{{$family->barangay?->name??'—'}}<div class="text-muted fs-7">{{$family->evacuationCenter?->name??'Unassigned'}}</div><div class="text-muted fs-8">{{$family->disaster?->name}}</div></td><td>{{$family->familyMembers->count()+1}} total<div class="text-muted fs-7">{{$family->familyMembers->count()}} additional members</div></td><td>{{$family->housing_condition}}<div class="text-muted fs-7">{{$family->house_ownership}}</div></td><td>@include('disaster.partials.status-badge',['status'=>$family->status->value])</td><td><span class="badge badge-light-{{$payout?->status==='Released'?'success':($payout?'warning':'secondary')}}">{{$payout?->status??'Not Ready'}}</span></td><td class="text-end"><a href="{{route('disaster.families.show',$family)}}" class="btn btn-sm btn-light-primary">Open</a></td></tr>
@empty<tr><td colspan="7"><div class="text-center py-12"><i class="ki-duotone ki-document fs-3x text-muted"><span class="path1"></span><span class="path2"></span></i><h4 class="mt-4 mb-1">No matching records</h4><div class="text-muted">Adjust or clear the report filters and try again.</div></div></td></tr>@endforelse
</tbody></table></div><div class="d-flex justify-content-end mt-6">{{$families->links()}}</div></div></div>
@endsection

@push('styles')<style>
.report-address{max-width:280px}.report-table{min-height:260px}@media print{.app-header,.app-sidebar,.report-filters,.card-toolbar,.pagination{display:none!important}.app-main{margin:0!important}.card{box-shadow:none!important;border:0!important}.report-table{overflow:visible!important}}
</style>@endpush
